Fix shadowed airlines test mock data
Fix a bug with how Nock mock test server assigns one set of data to a
stubbed out external URL; e.g. `/airlines`; and bleeds that data across
test scripts. This fix adjusts the mocked airlines data within the
`FlightAPISpec.js` so that the `serverSpec.js` tests can work along side
one another, rather than on their own.

== Notes:
- It is unknown how Nock will behave on our systems, since it may mock
  the dataset in a different order than this time causing tests to fail

- Dates were adjusted so that the data is slightly more unique between
  tests

- BEFORE

  ```
    ❯ npm test

    > locomotive_code_task@1.0.0 test /Users/Sonna/Projects/code_tasks/locomote_code_task_clone
    > jasmine

    Started
    ...................F.................................................F.............

    Failures:
    1) SearchForm component default props has internal props
      Message:
        SyntaxError: Unexpected token u in JSON at position 0
      Stack:
        SyntaxError: Unexpected token u in JSON at position 0
            at Object.parse (native)
            at Request._callback (/Users/Sonna/Projects/code_tasks/locomote_code_task_clone/lib/services/FlightAPI.js:59:23)
            at self.callback (/Users/Sonna/Projects/code_tasks/locomote_code_task_clone/node_modules/request/request.js:188:22)
            at emitOne (events.js:96:13)
            at Request.emit (events.js:188:7)
            at Request.onRequestError (/Users/Sonna/Projects/code_tasks/locomote_code_task_clone/node_modules/request/request.js:884:8)
            at emitOne (events.js:96:13)
            at OverriddenClientRequest.emit (events.js:188:7)
            at /Users/Sonna/Projects/code_tasks/locomote_code_task_clone/node_modules/nock/lib/request_overrider.js:207:11
            at _combinedTickCallback (internal/process/next_tick.js:73:7)
      Message:
        SyntaxError: Unexpected token u in JSON at position 0
      Stack:
        SyntaxError: Unexpected token u in JSON at position 0
            at Object.parse (native)
            at Request._callback (/Users/Sonna/Projects/code_tasks/locomote_code_task_clone/lib/services/FlightAPI.js:59:23)
            at self.callback (/Users/Sonna/Projects/code_tasks/locomote_code_task_clone/node_modules/request/request.js:188:22)
            at emitOne (events.js:96:13)
            at Request.emit (events.js:188:7)
            at Request.onRequestError (/Users/Sonna/Projects/code_tasks/locomote_code_task_clone/node_modules/request/request.js:884:8)
            at emitOne (events.js:96:13)
            at OverriddenClientRequest.emit (events.js:188:7)
            at /Users/Sonna/Projects/code_tasks/locomote_code_task_clone/node_modules/nock/lib/request_overrider.js:207:11
            at _combinedTickCallback (internal/process/next_tick.js:73:7)

    2) FlightAPI library search asyncSearchPreamble returns expected mocked search flight data
      Message:
        Expected [ Object({ code: 'FB', name: 'FooBar' }), Object({ code: 'BF', name: 'BarFoo' }), Object({ code: 'BB', name: 'BazBar' }), Object({ code: 'SU', name: 'Aeroflot' }), Object({ code: 'MU', name: 'China Eastern' }), Object({ code: 'EK', name: 'Emirates' }), Object({ code: 'KE', name: 'Korean Air lines' }), Object({ code: 'QF', name: 'Qantas' }), Object({ code: 'SQ', name: 'Singapore Airlines' }) ] to equal [ Object({ code: 'FB', name: 'FooBar' }), Object({ code: 'SU', name: 'Aeroflot' }), Object({ code: 'MU', name: 'China Eastern' }), Object({ code: 'EK', name: 'Emirates' }), Object({ code: 'KE', name: 'Korean Air lines' }), Object({ code: 'QF', name: 'Qantas' }), Object({ code: 'SQ', name: 'Singapore Airlines' }) ].
      Stack:
        Error: Expected [ Object({ code: 'FB', name: 'FooBar' }), Object({ code: 'BF', name: 'BarFoo' }), Object({ code: 'BB', name: 'BazBar' }), Object({ code: 'SU', name: 'Aeroflot' }), Object({ code: 'MU', name: 'China Eastern' }), Object({ code: 'EK', name: 'Emirates' }), Object({ code: 'KE', name: 'Korean Air lines' }), Object({ code: 'QF', name: 'Qantas' }), Object({ code: 'SQ', name: 'Singapore Airlines' }) ] to equal [ Object({ code: 'FB', name: 'FooBar' }), Object({ code: 'SU', name: 'Aeroflot' }), Object({ code: 'MU', name: 'China Eastern' }), Object({ code: 'EK', name: 'Emirates' }), Object({ code: 'KE', name: 'Korean Air lines' }), Object({ code: 'QF', name: 'Qantas' }), Object({ code: 'SQ', name: 'Singapore Airlines' }) ].
            at /Users/Sonna/Projects/code_tasks/locomote_code_task_clone/spec/lib/services/FlightAPISpec.js:1166:33
            at process._tickCallback (internal/process/next_tick.js:109:7)

    83 specs, 3 failures
    Finished in 0.517 seconds

    An error was thrown in an afterAll
    AfterAll SyntaxError: Unexpected token u in JSON at position 0
    An error was thrown in an afterAll
    AfterAll SyntaxError: Unexpected token u in JSON at position 0

    npm ERR! Test failed.  See above for more details.
  ```

  AFTER:

  ```
    ❯ npm test

    > locomotive_code_task@1.0.0 test /Users/Sonna/Projects/code_tasks/locomote_code_task_clone
    > jasmine

    Started
    ...................................................................................

    83 specs, 0 failures
    Finished in 0.436 seconds
  ```